# Generated by Django 5.2.4 on 2025-07-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
