# Generated by Django 5.0.14 on 2025-07-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=200)),
                ('schoolAddress', models.CharField(max_length=200)),
                ('schoolEstablished', models.IntegerField()),
                ('schoolEstablisher', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
